[package]
name = "extra_atomics"
version = "0.1.1"
edition = "2018"
license = "Apache-2.0"
description = "Abstraction over atomic ptr. Such as AtomicBox and AtomicArc."
repository = "https://github.com/domcx/extra_atomics"

[dependencies]
